/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.usj.musicquizzapi.model;

import com.usj.musicquizzapi.model.Song;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Song
 */
public class SongTest {
    private final Song model = new Song();

    /**
     * Model tests for Song
     */
    @Test
    public void testSong() {
        // TODO: test Song
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'lenght'
     */
    @Test
    public void lenghtTest() {
        // TODO: test lenght
    }

}
