/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.usj.musicquizzapi.model;

import com.usj.musicquizzapi.model.SongDTO;

import org.junit.jupiter.api.Test;

/**
 * Model tests for SongDTO
 */
public class SongDTOTest {
    private final SongDTO model = new SongDTO();

    /**
     * Model tests for SongDTO
     */
    @Test
    public void testSongDTO() {
        // TODO: test SongDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

}
