/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.usj.musicquizz.api;

import com.usj.musicquizz.invoker.ApiException;
import com.usj.musicquizz.model.SongDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SongControllerApiImplApi
 */
@Disabled
public class SongControllerApiImplApiTest {

    private final SongControllerApiImplApi api = new SongControllerApiImplApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSongTest() throws ApiException {
        SongDTO songDTO = null;
        SongDTO response = api.createSong(songDTO);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSongsTest() throws ApiException {
        Integer limit = null;
        Long offset = null;
        List<SongDTO> response = api.getSongs(limit, offset);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSongTest() throws ApiException {
        SongDTO songDTO = null;
        SongDTO response = api.updateSong(songDTO);
        // TODO: test validations
    }

}
